version: '3.8'

services:
  app:
    container_name: sciety_app
    build:
      context: ""
    environment:
      ALLOW_SITE_CRAWLERS: "true"
      APP_ORIGIN: "http://localhost:8080"
      APP_SECRET: "secret"
      APP_CACHE: '${APP_CACHE:-in-memory}'
      AUTHENTICATION_STRATEGY: '${AUTHENTICATION_STRATEGY:-twitter}'
      CROSSREF_API_BEARER_TOKEN:
      DISABLE_COOKIEBOT: '${DISABLE_COOKIEBOT}'
      EXPERIMENT_ENABLED: "true"
      FATHOM_SITE_ID:
      GOOGLE_TAG_MANAGER_ID:
      INGEST_LOG:
      LOG_LEVEL:
      PGUSER: user
      PGHOST: db
      PGPASSWORD: secret
      PGDATABASE: sciety
      PRELIGHTS_FEED_KEY:
      REDIS_HOST: sciety_cache
      TWITTER_API_KEY: '${TWITTER_API_KEY:-twitter-api-key}'
      TWITTER_API_SECRET_KEY: '${TWITTER_API_SECRET_KEY:-twitter-api-secret-key}'
      TWITTER_API_BEARER_TOKEN: '${TWITTER_API_BEARER_TOKEN:-twitter-api-bearer-token}'
    ports:
      - '8080:80'
    restart: unless-stopped
  db:
    container_name: sciety_db
    image: postgres:12.3-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: sciety
    healthcheck:
      test: pg_isready --username $$POSTGRES_USER --dbnam $$POSTGRES_DB || exit 1
      interval: 5s
  cache:
    container_name: sciety_cache
    image: redis:6.2-alpine
